#!/bin/bash

# Create simple placeholder icons using base64-encoded minimal PNG data
# These are valid 1x1 red pixel PNGs that will be scaled

cd "$(dirname "$0")/icons"

# Create a simple red pixel PNG (base64)
# This is a valid 16x16 red square PNG
cat << 'EOF' | base64 -d > icon16.png
iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAHElEQVR42mP4z8DwHwyZGBgY
/jMwMPxnABPMDABAvgIBAc6JCQAAAABJRU5ErkJggg==
EOF

# Create 32x32
cat << 'EOF' | base64 -d > icon32.png
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAMElEQVR42u3NMQ0AAAgDsOHf
NKRjhrQaBUh3Vv4qEAgEAoFAIBAIBAKBQCAQCP4LF/paAh2i1N0zAAAAAElFTkSuQmCC
EOF

# Create 48x48
cat << 'EOF' | base64 -d > icon48.png
iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAARUlEQVR42u3PwQ0AIAgEQJJ/
0x4bqQVQQs69Bm4SBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE3wV80AEr3fvr
dAAAAABJRU5ErkJggg==
EOF

# Create 128x128
cat << 'EOF' | base64 -d > icon128.png
iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAApElEQVR42u3BAQ0AAAgDoL+/
6SEwgjYwPPQJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUF
BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUF
BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQV9awABo27fTgAAAABJRU5E
rkJggg==
EOF

echo "Created placeholder icon files"
ls -lh
